# generated by datamodel-codegen:
#   filename:  predict_v0.json
#   timestamp: 2023-04-27T19:00:47+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Model(BaseModel):
    OPERA_Aerolineas_Argentinas: int = Field(..., alias='OPERA_Aerolineas Argentinas')
    OPERA_Aeromexico: int
    OPERA_Air_Canada: int = Field(..., alias='OPERA_Air Canada')
    OPERA_Air_France: int = Field(..., alias='OPERA_Air France')
    OPERA_Alitalia: int
    OPERA_American_Airlines: int = Field(..., alias='OPERA_American Airlines')
    OPERA_Austral: int
    OPERA_Avianca: int
    OPERA_British_Airways: int = Field(..., alias='OPERA_British Airways')
    OPERA_Copa_Air: int = Field(..., alias='OPERA_Copa Air')
    OPERA_Delta_Air: int = Field(..., alias='OPERA_Delta Air')
    OPERA_Gol_Trans: int = Field(..., alias='OPERA_Gol Trans')
    OPERA_Grupo_LATAM: int = Field(..., alias='OPERA_Grupo LATAM')
    OPERA_Iberia: int
    OPERA_JetSmart_SPA: int = Field(..., alias='OPERA_JetSmart SPA')
    OPERA_K_L_M_: int = Field(..., alias='OPERA_K.L.M.')
    OPERA_Lacsa: int
    OPERA_Latin_American_Wings: int = Field(..., alias='OPERA_Latin American Wings')
    OPERA_Oceanair_Linhas_Aereas: int = Field(..., alias='OPERA_Oceanair Linhas Aereas')
    OPERA_Plus_Ultra_Lineas_Aereas: int = Field(
        ..., alias='OPERA_Plus Ultra Lineas Aereas'
    )
    OPERA_Qantas_Airways: int = Field(..., alias='OPERA_Qantas Airways')
    OPERA_Sky_Airline: int = Field(..., alias='OPERA_Sky Airline')
    OPERA_United_Airlines: int = Field(..., alias='OPERA_United Airlines')
    TIPOVUELO_I: int
    TIPOVUELO_N: int
    MES_1: int
    MES_2: int
    MES_3: int
    MES_4: int
    MES_5: int
    MES_6: int
    MES_7: int
    MES_8: int
    MES_9: int
    MES_10: int
    MES_11: int
    MES_12: int
    PERIODO_mañana: int
    PERIODO_noche: int
    PERIODO_tarde: int
    DIA_Domingo: int
    DIA_Jueves: int
    DIA_Lunes: int
    DIA_Martes: int
    DIA_Miercoles: int
    DIA_Sabado: int
    DIA_Viernes: int
    DESTINO_Antofagasta: int
    DESTINO_Arica: int
    DESTINO_Asuncion: int
    DESTINO_Atlanta: int
    DESTINO_Auckland_N_Z_: int = Field(..., alias='DESTINO_Auckland N.Z.')
    DESTINO_Balmaceda: int
    DESTINO_Bariloche: int
    DESTINO_Bogota: int
    DESTINO_Buenos_Aires: int = Field(..., alias='DESTINO_Buenos Aires')
    DESTINO_Calama: int
    DESTINO_Cancun: int
    DESTINO_Castro__Chiloe_: int = Field(..., alias='DESTINO_Castro (Chiloe)')
    DESTINO_Cataratas_Iguacu: int = Field(..., alias='DESTINO_Cataratas Iguacu')
    DESTINO_Ciudad_de_Mexico: int = Field(..., alias='DESTINO_Ciudad de Mexico')
    DESTINO_Ciudad_de_Panama: int = Field(..., alias='DESTINO_Ciudad de Panama')
    DESTINO_Concepcion: int
    DESTINO_Copiapo: int
    DESTINO_Cordoba: int
    DESTINO_Dallas: int
    DESTINO_Florianapolis: int
    DESTINO_Guayaquil: int
    DESTINO_Houston: int
    DESTINO_Iquique: int
    DESTINO_Isla_de_Pascua: int = Field(..., alias='DESTINO_Isla de Pascua')
    DESTINO_La_Paz: int = Field(..., alias='DESTINO_La Paz')
    DESTINO_La_Serena: int = Field(..., alias='DESTINO_La Serena')
    DESTINO_Lima: int
    DESTINO_Londres: int
    DESTINO_Los_Angeles: int = Field(..., alias='DESTINO_Los Angeles')
    DESTINO_Madrid: int
    DESTINO_Melbourne: int
    DESTINO_Mendoza: int
    DESTINO_Miami: int
    DESTINO_Montevideo: int
    DESTINO_Neuquen: int
    DESTINO_Nueva_York: int = Field(..., alias='DESTINO_Nueva York')
    DESTINO_Orlando: int
    DESTINO_Osorno: int
    DESTINO_Paris: int
    DESTINO_Puerto_Montt: int = Field(..., alias='DESTINO_Puerto Montt')
    DESTINO_Puerto_Natales: int = Field(..., alias='DESTINO_Puerto Natales')
    DESTINO_Puerto_Stanley: int = Field(..., alias='DESTINO_Puerto Stanley')
    DESTINO_Punta_Arenas: int = Field(..., alias='DESTINO_Punta Arenas')
    DESTINO_Punta_Cana: int = Field(..., alias='DESTINO_Punta Cana')
    DESTINO_Punta_del_Este: int = Field(..., alias='DESTINO_Punta del Este')
    DESTINO_Rio_de_Janeiro: int = Field(..., alias='DESTINO_Rio de Janeiro')
    DESTINO_Roma: int
    DESTINO_Rosario: int
    DESTINO_San_Juan__Arg_: int = Field(..., alias='DESTINO_San Juan, Arg.')
    DESTINO_Santa_Cruz: int = Field(..., alias='DESTINO_Santa Cruz')
    DESTINO_Sao_Paulo: int = Field(..., alias='DESTINO_Sao Paulo')
    DESTINO_Sydney: int
    DESTINO_Temuco: int
    DESTINO_Toronto: int
    DESTINO_Tucuman: int
    DESTINO_Ushuia: int
    DESTINO_Valdivia: int
    temporada_alta: int
    hora: int
    VUELOS_PROGRAMADOS_DIA: int = Field(..., alias='VUELOS-PROGRAMADOS-DIA')
    RANKING_DIA: int
    FRACCION_RANKING_DIA: float
